# ports: HOST:CONTAINER
version: '3.8'
services:
    clash-meta-master:
        image: hub.hamdocker.ir/metacubex/clash-meta:v1.16.0
        container_name: clash-meta-master
        hostname: clash-meta-master
        entrypoint: ""
        command: "./clash -f config.yaml"
        restart: unless-stopped
        devices:
            - /dev/net/tun
        cap_add:
            - NET_ADMIN
        ports:
            - "1085:1080" # SOCKS PORT
            - "8585:8585" # VMESS PORT
        volumes:
            - ./config-master.yaml:/config.yaml


    clash-meta-slave-1:
        image: hub.hamdocker.ir/metacubex/clash-meta:v1.16.0
        container_name: clash-meta-slave-1
        hostname: clash-meta-slave-1
        entrypoint: ""
        command: "./clash -f config.yaml"
        restart: unless-stopped
        devices:
            - /dev/net/tun
        cap_add:
            - NET_ADMIN
        volumes:
            - ./config-slave-1.yaml:/config.yaml

    clash-meta-slave-2:
        image: hub.hamdocker.ir/metacubex/clash-meta:v1.16.0
        container_name: clash-meta-slave-2
        hostname: clash-meta-slave-2
        entrypoint: ""
        command: "./clash -f config.yaml"
        restart: unless-stopped
        devices:
            - /dev/net/tun
        cap_add:
            - NET_ADMIN
        volumes:
            - ./config-slave-2.yaml:/config.yaml

    clash-meta-slave-3:
        image: hub.hamdocker.ir/metacubex/clash-meta:v1.16.0
        container_name: clash-meta-slave-3
        hostname: clash-meta-slave-3
        entrypoint: ""
        command: "./clash -f config.yaml"
        restart: unless-stopped
        devices:
            - /dev/net/tun
        cap_add:
            - NET_ADMIN
        volumes:
            - ./config-slave-3.yaml:/config.yaml

    clash-meta-slave-4:
        image: hub.hamdocker.ir/metacubex/clash-meta:v1.16.0
        container_name: clash-meta-slave-4
        hostname: clash-meta-slave-4
        entrypoint: ""
        command: "./clash -f config.yaml"
        restart: unless-stopped
        devices:
            - /dev/net/tun
        cap_add:
            - NET_ADMIN
        volumes:
            - ./config-slave-4.yaml:/config.yaml

    clash-meta-slave-5:
        image: hub.hamdocker.ir/metacubex/clash-meta:v1.16.0
        container_name: clash-meta-slave-5
        hostname: clash-meta-slave-5
        entrypoint: ""
        command: "./clash -f config.yaml"
        restart: unless-stopped
        devices:
            - /dev/net/tun
        cap_add:
            - NET_ADMIN
        volumes:
            - ./config-slave-5.yaml:/config.yaml

