# ports: HOST:CONTAINER
version: '3.8'
services:
    clash-meta-master:
        build: .
        container_name: clash-meta-master
        hostname: clash-meta-master
        entrypoint: ""
        command: "/masterRun.sh"
        environment:
            MASTER_SOCKS_PORT: 1080
            MASTER_SOCKS_USERNAME: root
            MASTER_SOCKS_PASSWORD: 123456789
            MASTER_VMESS_PORT: 8585
            MASTER_VMESS_USERNAME: root
            MASTER_VMESS_UUID: 8a43af54-70d4-4b7c-b2db-458daf15e3e5
            SLAVE_PROXIES: socks5://username:pass@clash-meta-slave-1:5001,socks5://username:pass@clash-meta-slave-2:5002,socks5://username:pass@clash-meta-slave-3:5003,socks5://username:pass@clash-meta-slave-4:5004,socks5://username:pass@clash-meta-slave-5:5005
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        ports:
            - "1085:1080" # SOCKS PORT
            - "8585:8585" # VMESS PORT


    clash-meta-slave-1:
        build: .
        container_name: clash-meta-slave-1
        hostname: clash-meta-slave-1
        command: "/slaveRun.sh"
        environment:
            SLAVE_SOCKS_PORT: 5001
        restart: unless-stopped
        cap_add:
            - NET_ADMIN

    clash-meta-slave-2:
        build: .
        container_name: clash-meta-slave-2
        hostname: clash-meta-slave-2
        command: "/slaveRun.sh"
        environment:
            SLAVE_SOCKS_PORT: 5002
        restart: unless-stopped
        cap_add:
            - NET_ADMIN


    clash-meta-slave-3:
        build: .
        container_name: clash-meta-slave-3
        hostname: clash-meta-slave-3
        command: "/slaveRun.sh"
        environment:
            SLAVE_SOCKS_PORT: 5003
        restart: unless-stopped
        cap_add:
            - NET_ADMIN


    clash-meta-slave-4:
        build: .
        container_name: clash-meta-slave-4
        hostname: clash-meta-slave-4
        command: "/slaveRun.sh"
        environment:
            SLAVE_SOCKS_PORT: 5004
        restart: unless-stopped
        cap_add:
            - NET_ADMIN


    clash-meta-slave-5:
        build: .
        container_name: clash-meta-slave-5
        hostname: clash-meta-slave-5
        command: "/slaveRun.sh"
        environment:
            SLAVE_SOCKS_PORT: 5005
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
