# ports: HOST:CONTAINER
version: '3.8'
services:
    clash-meta:
        build: .
        container_name: clash-meta
        hostname: clash-meta
        entrypoint: ""
        command: "./clash -f config.yaml"
        restart: unless-stopped
        healthcheck:
            test: /validateIp $(curl -s -x socks5://root:PASSWORD_SHOULD_BE_CHANGED@127.0.0.1:1080 --connect-timeout 5 --max-time 4 --retry 3 --retry-delay 0 --retry-max-time 16 ident.me) || kill 1
            interval: 5s
            retries: 2
            start_period: 60s
            timeout: 20s
        devices:
            - /dev/net/tun
        cap_add:
            - NET_ADMIN
        ports:
          - "1085:1080" # SOCKS PORT
          - "8585:8585" # VMESS PORT
          - "9090:9090" # API PORT
        volumes:
            - ./config.yaml:/config.yaml
            - ./validateIp:/root/validateIp

    metacubexd:
        container_name: metacubexd
        image: ghcr.io/metacubex/metacubexd
        restart: always
        ports:
            - '8085:80'
